/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Aprendiz
 */
public class Pedidos extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Pedidos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Inventario_PanelFondo = new javax.swing.JPanel();
        Inventario_PanelFondoRegistro = new javax.swing.JPanel();
        Inventario_ConPaneles = new javax.swing.JPanel();
        Inventario_Campos = new javax.swing.JPanel();
        Inventario_TituloProveedor = new javax.swing.JComboBox<>();
        Inventario_CampoCodigo = new javax.swing.JTextField();
        Inventario_CampoDescripcion = new javax.swing.JTextField();
        Inventario_CampoCantidad = new javax.swing.JTextField();
        Inventario_CampoPrecio = new javax.swing.JTextField();
        Inventario_TituloCodigo = new javax.swing.JLabel();
        Inventario_TituloDescripcion = new javax.swing.JLabel();
        Inventario_TituloCantidad = new javax.swing.JLabel();
        Inventario_TituloPrecio = new javax.swing.JLabel();
        Inventario_BotonGuardar = new javax.swing.JButton();
        Inventario_ScrollTabla = new javax.swing.JScrollPane();
        Inventario_Tabla = new javax.swing.JTable();
        Inventario_Titulo = new javax.swing.JLabel();
        Inventario_Buscador = new javax.swing.JTextField();
        Inventario_IconoBuscador = new javax.swing.JLabel();
        Menu_PanelMenu = new javax.swing.JPanel();
        Menu_Foto = new javax.swing.JLabel();
        Menu_Inicio = new javax.swing.JLabel();
        Menu_Clientes = new javax.swing.JLabel();
        Menu_Proveedor = new javax.swing.JLabel();
        Menu_Facturas = new javax.swing.JLabel();
        Menu_Separador2 = new javax.swing.JSeparator();
        Menu_Salir = new javax.swing.JLabel();
        Menu_Roles = new javax.swing.JLabel();
        Menu_Separador3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Inventario_PanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Inventario_PanelFondoRegistro.setBackground(new java.awt.Color(255, 255, 255));
        Inventario_PanelFondoRegistro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Inventario_ConPaneles.setBackground(new java.awt.Color(204, 204, 204));
        Inventario_ConPaneles.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Inventario_ConPaneles.setMinimumSize(new java.awt.Dimension(130, 430));
        Inventario_ConPaneles.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Inventario_Campos.setBackground(new java.awt.Color(255, 255, 255));
        Inventario_Campos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Inventario_TituloProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Proveedor", "Item 1", "Item 2", "Item 3", "Item 4" }));

        Inventario_TituloCodigo.setText("Codigo");

        Inventario_TituloDescripcion.setText("Descripcion");

        Inventario_TituloCantidad.setText("Cantidad");

        Inventario_TituloPrecio.setText("Precio");

        Inventario_BotonGuardar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Inventario_BotonGuardar.setText("Ingresar");
        Inventario_BotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inventario_BotonGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Inventario_CamposLayout = new javax.swing.GroupLayout(Inventario_Campos);
        Inventario_Campos.setLayout(Inventario_CamposLayout);
        Inventario_CamposLayout.setHorizontalGroup(
            Inventario_CamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Inventario_CamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Inventario_CamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Inventario_TituloProveedor, 0, 166, Short.MAX_VALUE)
                    .addComponent(Inventario_CampoCodigo)
                    .addComponent(Inventario_CampoDescripcion)
                    .addComponent(Inventario_CampoCantidad)
                    .addComponent(Inventario_CampoPrecio)
                    .addGroup(Inventario_CamposLayout.createSequentialGroup()
                        .addGroup(Inventario_CamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Inventario_TituloCodigo)
                            .addComponent(Inventario_TituloDescripcion)
                            .addComponent(Inventario_TituloCantidad)
                            .addComponent(Inventario_TituloPrecio))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Inventario_BotonGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Inventario_CamposLayout.setVerticalGroup(
            Inventario_CamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Inventario_CamposLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(Inventario_TituloCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Inventario_CampoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(Inventario_TituloDescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Inventario_CampoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(Inventario_TituloCantidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Inventario_CampoCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(Inventario_TituloPrecio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Inventario_CampoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(Inventario_TituloProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addComponent(Inventario_BotonGuardar)
                .addGap(31, 31, 31))
        );

        Inventario_ConPaneles.add(Inventario_Campos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 770));

        Inventario_ScrollTabla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Inventario_Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Descripcion", "Cantidad", "Precio", "Proveedor"
            }
        ));
        Inventario_ScrollTabla.setViewportView(Inventario_Tabla);

        Inventario_ConPaneles.add(Inventario_ScrollTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 1210, 770));

        Inventario_Titulo.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Inventario_Titulo.setText("Registro Pedidos");

        Inventario_Buscador.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Inventario_Buscador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Inventario_IconoBuscador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentes/img/buscadorIcon.png"))); // NOI18N

        javax.swing.GroupLayout Inventario_PanelFondoRegistroLayout = new javax.swing.GroupLayout(Inventario_PanelFondoRegistro);
        Inventario_PanelFondoRegistro.setLayout(Inventario_PanelFondoRegistroLayout);
        Inventario_PanelFondoRegistroLayout.setHorizontalGroup(
            Inventario_PanelFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Inventario_PanelFondoRegistroLayout.createSequentialGroup()
                .addGroup(Inventario_PanelFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Inventario_PanelFondoRegistroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Inventario_ConPaneles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Inventario_PanelFondoRegistroLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(Inventario_Titulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 910, Short.MAX_VALUE)
                        .addComponent(Inventario_IconoBuscador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Inventario_Buscador, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        Inventario_PanelFondoRegistroLayout.setVerticalGroup(
            Inventario_PanelFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Inventario_PanelFondoRegistroLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(Inventario_PanelFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Inventario_Titulo)
                    .addGroup(Inventario_PanelFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Inventario_Buscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Inventario_IconoBuscador)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Inventario_ConPaneles, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
                .addContainerGap())
        );

        Inventario_PanelFondo.add(Inventario_PanelFondoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 1360, 850));

        Menu_PanelMenu.setBackground(new java.awt.Color(255, 255, 255));
        Menu_PanelMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Menu_Foto.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Menu_Foto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Menu_Foto.setText("Foto");
        Menu_Foto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Menu_Inicio.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        Menu_Inicio.setText("Mesa");

        Menu_Clientes.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        Menu_Clientes.setText("Clientes");

        Menu_Proveedor.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        Menu_Proveedor.setText("Pedidos");

        Menu_Facturas.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        Menu_Facturas.setText("Crear Factura");

        Menu_Salir.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        Menu_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentes/img/salirIcon.png"))); // NOI18N
        Menu_Salir.setText("Salir");
        Menu_Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_SalirMouseClicked(evt);
            }
        });

        Menu_Roles.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Menu_Roles.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Menu_Roles.setText("ROLES");

        javax.swing.GroupLayout Menu_PanelMenuLayout = new javax.swing.GroupLayout(Menu_PanelMenu);
        Menu_PanelMenu.setLayout(Menu_PanelMenuLayout);
        Menu_PanelMenuLayout.setHorizontalGroup(
            Menu_PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu_Roles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Menu_PanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Menu_PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Menu_Foto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Menu_Separador2)
                    .addComponent(Menu_Facturas, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(Menu_Clientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Menu_Proveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Menu_Inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Menu_Salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Menu_Separador3))
                .addContainerGap())
        );
        Menu_PanelMenuLayout.setVerticalGroup(
            Menu_PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu_PanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Menu_Foto, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(Menu_Roles)
                .addGap(27, 27, 27)
                .addComponent(Menu_Separador3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(Menu_Inicio)
                .addGap(91, 91, 91)
                .addComponent(Menu_Proveedor)
                .addGap(96, 96, 96)
                .addComponent(Menu_Clientes)
                .addGap(97, 97, 97)
                .addComponent(Menu_Facturas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(Menu_Separador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(Menu_Salir)
                .addGap(24, 24, 24))
        );

        Inventario_PanelFondo.add(Menu_PanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 850));

        getContentPane().add(Inventario_PanelFondo, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Menu_SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_SalirMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Menu_SalirMouseClicked

    private void Inventario_BotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inventario_BotonGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Inventario_BotonGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Inventario_BotonGuardar;
    private javax.swing.JTextField Inventario_Buscador;
    private javax.swing.JTextField Inventario_CampoCantidad;
    private javax.swing.JTextField Inventario_CampoCodigo;
    private javax.swing.JTextField Inventario_CampoDescripcion;
    private javax.swing.JTextField Inventario_CampoPrecio;
    private javax.swing.JPanel Inventario_Campos;
    private javax.swing.JPanel Inventario_ConPaneles;
    private javax.swing.JLabel Inventario_IconoBuscador;
    private javax.swing.JPanel Inventario_PanelFondo;
    private javax.swing.JPanel Inventario_PanelFondoRegistro;
    private javax.swing.JScrollPane Inventario_ScrollTabla;
    private javax.swing.JTable Inventario_Tabla;
    private javax.swing.JLabel Inventario_Titulo;
    private javax.swing.JLabel Inventario_TituloCantidad;
    private javax.swing.JLabel Inventario_TituloCodigo;
    private javax.swing.JLabel Inventario_TituloDescripcion;
    private javax.swing.JLabel Inventario_TituloPrecio;
    private javax.swing.JComboBox<String> Inventario_TituloProveedor;
    private javax.swing.JLabel Menu_Clientes;
    private javax.swing.JLabel Menu_Facturas;
    private javax.swing.JLabel Menu_Foto;
    private javax.swing.JLabel Menu_Inicio;
    private javax.swing.JPanel Menu_PanelMenu;
    private javax.swing.JLabel Menu_Proveedor;
    private javax.swing.JLabel Menu_Roles;
    private javax.swing.JLabel Menu_Salir;
    private javax.swing.JSeparator Menu_Separador2;
    private javax.swing.JSeparator Menu_Separador3;
    // End of variables declaration//GEN-END:variables
}
