package vista;

import controlador.loginCtrl;
import javax.swing.JButton;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

public class ventanaLogin extends javax.swing.JFrame {

    public ventanaLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelContenedorLogin = new javax.swing.JPanel();
        TituloInicioSesion = new javax.swing.JLabel();
        BtnLogin = new javax.swing.JButton();
        OlvidasteContraseña = new javax.swing.JLabel();
        IconUsuario = new javax.swing.JLabel();
        IconContraseña = new javax.swing.JLabel();
        ImgFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelContenedorLogin.setBackground(new java.awt.Color(0, 0, 0, 0));
        PanelContenedorLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelContenedorLogin.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        PanelContenedorLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TituloInicioSesion.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        TituloInicioSesion.setForeground(new java.awt.Color(255, 255, 255));
        TituloInicioSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloInicioSesion.setText("Iniciar Sesión");
        PanelContenedorLogin.add(TituloInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 420, 170));

        BtnLogin.setBackground(new java.awt.Color(22, 18, 38));
        BtnLogin.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        BtnLogin.setForeground(new java.awt.Color(255, 255, 255));
        BtnLogin.setText("INGRESAR");
        PanelContenedorLogin.add(BtnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 453, 230, 40));

        OlvidasteContraseña.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OlvidasteContraseña.setText("¿ Olvidaste tu contraseña ?");
        PanelContenedorLogin.add(OlvidasteContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 408, 230, -1));

        IconUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentes/img/UserIcon.png"))); // NOI18N
        PanelContenedorLogin.add(IconUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 235, -1, 26));

        IconContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentes/img/PasswordIcon.png"))); // NOI18N
        PanelContenedorLogin.add(IconContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 355, -1, 37));

        getContentPane().add(PanelContenedorLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 420, 560));

        ImgFondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImgFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentes/img/Fondo_Login.gif"))); // NOI18N
        getContentPane().add(ImgFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
        ventanaLogin login = new ventanaLogin();
        loginCtrl lox = new loginCtrl(login);
        login.setVisible(true);
                //new ventanaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnLogin;
    private javax.swing.JLabel IconContraseña;
    private javax.swing.JLabel IconUsuario;
    private javax.swing.JLabel ImgFondo;
    private javax.swing.JLabel OlvidasteContraseña;
    private javax.swing.JPanel PanelContenedorLogin;
    private javax.swing.JLabel TituloInicioSesion;
    // End of variables declaration//GEN-END:variables

    public  JButton getBtnLogin() {
        return BtnLogin;
    }

    public  JPasswordField getCampoContraseña() {
        return null;
    }

    public  JTextField getCampoUsuario() {
        return null;
    }
}