package vista;

import controlador.loginCtrl;
import javax.swing.JButton;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

public class ventanaLogin extends javax.swing.JFrame {

    public ventanaLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelContenedorLogin = new javax.swing.JPanel();
        TituloInicioSesion = new javax.swing.JLabel();
        BtnLogin = new javax.swing.JButton();
        OlvidasteContraseña = new javax.swing.JLabel();
        IconUsuario = new javax.swing.JLabel();
        IconContraseña = new javax.swing.JLabel();
        CampoUsuario = new componentes.TextField();
        CampoContraseña = new componentes.PasswordField();
        ImgFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelContenedorLogin.setBackground(new java.awt.Color(255, 255, 255));
        PanelContenedorLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelContenedorLogin.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        TituloInicioSesion.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        TituloInicioSesion.setForeground(new java.awt.Color(22, 18, 38));
        TituloInicioSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloInicioSesion.setText("Iniciar Sesión");

        BtnLogin.setBackground(new java.awt.Color(22, 18, 38));
        BtnLogin.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        BtnLogin.setForeground(new java.awt.Color(255, 255, 255));
        BtnLogin.setText("INGRESAR");

        OlvidasteContraseña.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OlvidasteContraseña.setText("¿ Olvidaste tu contraseña ?");

        IconUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentes/img/UserIcon.png"))); // NOI18N

        IconContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentes/img/PasswordIcon.png"))); // NOI18N

        CampoUsuario.setBackground(new java.awt.Color(255, 255, 255));
        CampoUsuario.setToolTipText("");
        CampoUsuario.setLabelText("Usuario");
        CampoUsuario.setLineColor(new java.awt.Color(22, 7, 38));

        CampoContraseña.setBackground(new java.awt.Color(255, 255, 255));
        CampoContraseña.setLabelText("Contraseña");
        CampoContraseña.setLineColor(new java.awt.Color(22, 7, 38));

        javax.swing.GroupLayout PanelContenedorLoginLayout = new javax.swing.GroupLayout(PanelContenedorLogin);
        PanelContenedorLogin.setLayout(PanelContenedorLoginLayout);
        PanelContenedorLoginLayout.setHorizontalGroup(
            PanelContenedorLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelContenedorLoginLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(PanelContenedorLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IconUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IconContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelContenedorLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(OlvidasteContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(BtnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(CampoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CampoContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelContenedorLoginLayout.createSequentialGroup()
                .addComponent(TituloInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        PanelContenedorLoginLayout.setVerticalGroup(
            PanelContenedorLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelContenedorLoginLayout.createSequentialGroup()
                .addComponent(TituloInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PanelContenedorLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelContenedorLoginLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(IconUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelContenedorLoginLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(CampoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(PanelContenedorLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelContenedorLoginLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(IconContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelContenedorLoginLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(OlvidasteContraseña)
                .addGap(29, 29, 29)
                .addComponent(BtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        getContentPane().add(PanelContenedorLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 410, 540));

        ImgFondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImgFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentes/img/fondo_4.jpg"))); // NOI18N
        getContentPane().add(ImgFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
        ventanaLogin login = new ventanaLogin();
        loginCtrl lox = new loginCtrl(login);
        login.setVisible(true);
                //new ventanaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnLogin;
    private componentes.PasswordField CampoContraseña;
    private componentes.TextField CampoUsuario;
    private javax.swing.JLabel IconContraseña;
    private javax.swing.JLabel IconUsuario;
    private javax.swing.JLabel ImgFondo;
    private javax.swing.JLabel OlvidasteContraseña;
    private javax.swing.JPanel PanelContenedorLogin;
    private javax.swing.JLabel TituloInicioSesion;
    // End of variables declaration//GEN-END:variables

    public  JButton getBtnLogin() {
        return BtnLogin;
    }

    public  JPasswordField getCampoContraseña() {
        return CampoContraseña;
    }

    public  JTextField getCampoUsuario() {
        return CampoUsuario;
    }
}