/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

/**
 *
 * @author Aprendiz
 */
public class Inventario extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inventario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Inventario_PanelFondo = new javax.swing.JPanel();
        Inventario_PanelMenu = new javax.swing.JPanel();
        Inventario_Foto = new javax.swing.JLabel();
        Inventario_Inicio = new javax.swing.JLabel();
        Inventario_Clientes = new javax.swing.JLabel();
        Inventario_Proveedor = new javax.swing.JLabel();
        Inventario_Inventario = new javax.swing.JLabel();
        Inventario_Separador = new javax.swing.JSeparator();
        Inventario_Facturas = new javax.swing.JLabel();
        Inventario_Separador2 = new javax.swing.JSeparator();
        Inventario_Ayuda = new javax.swing.JLabel();
        Inventario_Salir = new javax.swing.JLabel();
        Inventario_Roles = new javax.swing.JLabel();
        Inventario_PanelFondoRegistro = new javax.swing.JPanel();
        Inventario_ConPaneles = new javax.swing.JPanel();
        Inventario_Campos = new javax.swing.JPanel();
        Inventario_TituloProveedor = new javax.swing.JComboBox<>();
        Inventario_CampoCodigo = new javax.swing.JTextField();
        Inventario_CampoDescripcion = new javax.swing.JTextField();
        Inventario_CampoCantidad = new javax.swing.JTextField();
        Inventario_CampoPrecio = new javax.swing.JTextField();
        Inventario_TituloCodigo = new javax.swing.JLabel();
        Inventario_TituloDescripcion = new javax.swing.JLabel();
        Inventario_TituloCantidad = new javax.swing.JLabel();
        Inventario_TituloPrecio = new javax.swing.JLabel();
        Inventario_ScrollTabla = new javax.swing.JScrollPane();
        Inventario_Tabla = new javax.swing.JTable();
        Inventario_BotonActualizar = new javax.swing.JButton();
        Inventario_BotonEliminar = new javax.swing.JButton();
        Inventario_BotonGuardar = new javax.swing.JButton();
        Inventario_Titulo = new javax.swing.JLabel();
        Inventario_Buscador = new javax.swing.JTextField();
        Inventario_IconoBuscador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Inventario_PanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Inventario_PanelMenu.setBackground(new java.awt.Color(255, 255, 255));
        Inventario_PanelMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Inventario_Foto.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Inventario_Foto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Inventario_Foto.setText("Foto");
        Inventario_Foto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Inventario_Inicio.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Inventario_Inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentes/img/InicioIcon.png"))); // NOI18N
        Inventario_Inicio.setText("Inicio");

        Inventario_Clientes.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Inventario_Clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentes/img/ClientesIcon.png"))); // NOI18N
        Inventario_Clientes.setText("Clientes");

        Inventario_Proveedor.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Inventario_Proveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentes/img/proveedorIcon.png"))); // NOI18N
        Inventario_Proveedor.setText("Proveedor");

        Inventario_Inventario.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Inventario_Inventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentes/img/inventarioIcon.png"))); // NOI18N
        Inventario_Inventario.setText("Inventario");

        Inventario_Separador.setBackground(new java.awt.Color(255, 255, 255));
        Inventario_Separador.setForeground(new java.awt.Color(0, 0, 0));

        Inventario_Facturas.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Inventario_Facturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentes/img/facturaIcon.png"))); // NOI18N
        Inventario_Facturas.setText("Crear Factura");

        Inventario_Separador2.setBackground(new java.awt.Color(255, 255, 255));
        Inventario_Separador2.setForeground(new java.awt.Color(0, 0, 0));

        Inventario_Ayuda.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Inventario_Ayuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentes/img/ayudaIcon.png"))); // NOI18N
        Inventario_Ayuda.setText("Ayuda");

        Inventario_Salir.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Inventario_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentes/img/regresarIcon.png"))); // NOI18N
        Inventario_Salir.setText("Salir");
        Inventario_Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Inventario_SalirMouseClicked(evt);
            }
        });

        Inventario_Roles.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Inventario_Roles.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Inventario_Roles.setText("ROLES");

        javax.swing.GroupLayout Inventario_PanelMenuLayout = new javax.swing.GroupLayout(Inventario_PanelMenu);
        Inventario_PanelMenu.setLayout(Inventario_PanelMenuLayout);
        Inventario_PanelMenuLayout.setHorizontalGroup(
            Inventario_PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Inventario_PanelMenuLayout.createSequentialGroup()
                .addGroup(Inventario_PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Inventario_PanelMenuLayout.createSequentialGroup()
                        .addGroup(Inventario_PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Inventario_PanelMenuLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(Inventario_Facturas))
                            .addGroup(Inventario_PanelMenuLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(Inventario_PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Inventario_Ayuda)
                                    .addComponent(Inventario_Salir))))
                        .addGap(0, 82, Short.MAX_VALUE))
                    .addGroup(Inventario_PanelMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Inventario_PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Inventario_Separador2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Inventario_Separador, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Inventario_PanelMenuLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(Inventario_PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Inventario_Inventario)
                                    .addGroup(Inventario_PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Inventario_Clientes)
                                        .addComponent(Inventario_Inicio)
                                        .addComponent(Inventario_Proveedor)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(Inventario_PanelMenuLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(Inventario_PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Inventario_Foto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Inventario_Roles, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Inventario_PanelMenuLayout.setVerticalGroup(
            Inventario_PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Inventario_PanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Inventario_Foto, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Inventario_Roles)
                .addGap(20, 20, 20)
                .addComponent(Inventario_Inicio)
                .addGap(44, 44, 44)
                .addComponent(Inventario_Clientes)
                .addGap(39, 39, 39)
                .addComponent(Inventario_Proveedor)
                .addGap(46, 46, 46)
                .addComponent(Inventario_Inventario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Inventario_Separador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(Inventario_Facturas)
                .addGap(29, 29, 29)
                .addComponent(Inventario_Separador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(Inventario_Ayuda)
                .addGap(18, 18, 18)
                .addComponent(Inventario_Salir)
                .addGap(19, 19, 19))
        );

        Inventario_PanelFondo.add(Inventario_PanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 500));

        Inventario_PanelFondoRegistro.setBackground(new java.awt.Color(255, 255, 255));
        Inventario_PanelFondoRegistro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Inventario_ConPaneles.setBackground(new java.awt.Color(204, 204, 204));
        Inventario_ConPaneles.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Inventario_ConPaneles.setMinimumSize(new java.awt.Dimension(130, 430));
        Inventario_ConPaneles.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Inventario_Campos.setBackground(new java.awt.Color(255, 255, 255));
        Inventario_Campos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Inventario_TituloProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Proveedor", "Item 1", "Item 2", "Item 3", "Item 4" }));

        Inventario_TituloCodigo.setText("Codigo");

        Inventario_TituloDescripcion.setText("Descripcion");

        Inventario_TituloCantidad.setText("Cantidad");

        Inventario_TituloPrecio.setText("Precio");

        javax.swing.GroupLayout Inventario_CamposLayout = new javax.swing.GroupLayout(Inventario_Campos);
        Inventario_Campos.setLayout(Inventario_CamposLayout);
        Inventario_CamposLayout.setHorizontalGroup(
            Inventario_CamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Inventario_CamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Inventario_CamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Inventario_TituloProveedor, 0, 106, Short.MAX_VALUE)
                    .addComponent(Inventario_CampoCodigo)
                    .addComponent(Inventario_CampoDescripcion)
                    .addComponent(Inventario_CampoCantidad)
                    .addComponent(Inventario_CampoPrecio)
                    .addGroup(Inventario_CamposLayout.createSequentialGroup()
                        .addGroup(Inventario_CamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Inventario_TituloCodigo)
                            .addComponent(Inventario_TituloDescripcion)
                            .addComponent(Inventario_TituloCantidad)
                            .addComponent(Inventario_TituloPrecio))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Inventario_CamposLayout.setVerticalGroup(
            Inventario_CamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Inventario_CamposLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(Inventario_TituloCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Inventario_CampoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(Inventario_TituloDescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Inventario_CampoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(Inventario_TituloCantidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Inventario_CampoCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(Inventario_TituloPrecio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Inventario_CampoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(Inventario_TituloProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        Inventario_ConPaneles.add(Inventario_Campos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 380));

        Inventario_ScrollTabla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Inventario_Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Descripcion", "Cantidad", "Precio", "Proveedor"
            }
        ));
        Inventario_ScrollTabla.setViewportView(Inventario_Tabla);

        Inventario_ConPaneles.add(Inventario_ScrollTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 540, 380));

        Inventario_BotonActualizar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Inventario_BotonActualizar.setText("Actualizar");
        Inventario_BotonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inventario_BotonActualizarActionPerformed(evt);
            }
        });
        Inventario_ConPaneles.add(Inventario_BotonActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 130, -1));

        Inventario_BotonEliminar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Inventario_BotonEliminar.setText("Eliminar");
        Inventario_ConPaneles.add(Inventario_BotonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 130, -1));

        Inventario_BotonGuardar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Inventario_BotonGuardar.setText("Guardar");
        Inventario_ConPaneles.add(Inventario_BotonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 115, -1));

        Inventario_Titulo.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Inventario_Titulo.setText("Registro Inventario");

        Inventario_Buscador.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Inventario_Buscador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Inventario_IconoBuscador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentes/img/buscadorIcon.png"))); // NOI18N

        javax.swing.GroupLayout Inventario_PanelFondoRegistroLayout = new javax.swing.GroupLayout(Inventario_PanelFondoRegistro);
        Inventario_PanelFondoRegistro.setLayout(Inventario_PanelFondoRegistroLayout);
        Inventario_PanelFondoRegistroLayout.setHorizontalGroup(
            Inventario_PanelFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Inventario_PanelFondoRegistroLayout.createSequentialGroup()
                .addGroup(Inventario_PanelFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Inventario_PanelFondoRegistroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Inventario_ConPaneles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Inventario_PanelFondoRegistroLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(Inventario_Titulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                        .addComponent(Inventario_IconoBuscador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Inventario_Buscador, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        Inventario_PanelFondoRegistroLayout.setVerticalGroup(
            Inventario_PanelFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Inventario_PanelFondoRegistroLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(Inventario_PanelFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Inventario_Titulo)
                    .addGroup(Inventario_PanelFondoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Inventario_Buscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Inventario_IconoBuscador)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Inventario_ConPaneles, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                .addContainerGap())
        );

        Inventario_PanelFondo.add(Inventario_PanelFondoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 690, 500));

        getContentPane().add(Inventario_PanelFondo, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Inventario_SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Inventario_SalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_Inventario_SalirMouseClicked

    private void Inventario_BotonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inventario_BotonActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Inventario_BotonActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Inventario_Ayuda;
    private javax.swing.JButton Inventario_BotonActualizar;
    private javax.swing.JButton Inventario_BotonEliminar;
    private javax.swing.JButton Inventario_BotonGuardar;
    private javax.swing.JTextField Inventario_Buscador;
    private javax.swing.JTextField Inventario_CampoCantidad;
    private javax.swing.JTextField Inventario_CampoCodigo;
    private javax.swing.JTextField Inventario_CampoDescripcion;
    private javax.swing.JTextField Inventario_CampoPrecio;
    private javax.swing.JPanel Inventario_Campos;
    private javax.swing.JLabel Inventario_Clientes;
    private javax.swing.JPanel Inventario_ConPaneles;
    private javax.swing.JLabel Inventario_Facturas;
    private javax.swing.JLabel Inventario_Foto;
    private javax.swing.JLabel Inventario_IconoBuscador;
    private javax.swing.JLabel Inventario_Inicio;
    private javax.swing.JLabel Inventario_Inventario;
    private javax.swing.JPanel Inventario_PanelFondo;
    private javax.swing.JPanel Inventario_PanelFondoRegistro;
    private javax.swing.JPanel Inventario_PanelMenu;
    private javax.swing.JLabel Inventario_Proveedor;
    private javax.swing.JLabel Inventario_Roles;
    private javax.swing.JLabel Inventario_Salir;
    private javax.swing.JScrollPane Inventario_ScrollTabla;
    private javax.swing.JSeparator Inventario_Separador;
    private javax.swing.JSeparator Inventario_Separador2;
    private javax.swing.JTable Inventario_Tabla;
    private javax.swing.JLabel Inventario_Titulo;
    private javax.swing.JLabel Inventario_TituloCantidad;
    private javax.swing.JLabel Inventario_TituloCodigo;
    private javax.swing.JLabel Inventario_TituloDescripcion;
    private javax.swing.JLabel Inventario_TituloPrecio;
    private javax.swing.JComboBox<String> Inventario_TituloProveedor;
    // End of variables declaration//GEN-END:variables
}
