package Interfaces;

import javax.swing.JOptionPane;

public class Menu extends javax.swing.JFrame {

    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu_PanelFondo = new javax.swing.JPanel();
        Menu_PanelMenu = new javax.swing.JPanel();
        Menu_Foto = new javax.swing.JLabel();
        Menu_Inicio = new javax.swing.JLabel();
        Menu_Clientes = new javax.swing.JLabel();
        Menu_Proveedor = new javax.swing.JLabel();
        Menu_Inventario = new javax.swing.JLabel();
        Menu_Separador = new javax.swing.JSeparator();
        Menu_Facturas = new javax.swing.JLabel();
        Menu_Separador2 = new javax.swing.JSeparator();
        Menu_Ayuda = new javax.swing.JLabel();
        Menu_Salir = new javax.swing.JLabel();
        Menu_Roles = new javax.swing.JLabel();
        Menu_ConPaneles = new javax.swing.JPanel();
        Menu_PanelClientes = new javax.swing.JPanel();
        Menu_TituloClientes = new javax.swing.JLabel();
        Menu_TituloTotal = new javax.swing.JLabel();
        Menu_PanelProductos = new javax.swing.JPanel();
        Menu_TituloProductos = new javax.swing.JLabel();
        Menu_TituloTotal2 = new javax.swing.JLabel();
        Menu_PanelPresentacion = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Menu_PanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu_PanelMenu.setBackground(new java.awt.Color(255, 255, 255));
        Menu_PanelMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Menu_Foto.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Menu_Foto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Menu_Foto.setText("Foto");
        Menu_Foto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Menu_Inicio.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Menu_Inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentes/img/InicioIcon.png"))); // NOI18N
        Menu_Inicio.setText("Inicio");

        Menu_Clientes.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Menu_Clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentes/img/ClientesIcon.png"))); // NOI18N
        Menu_Clientes.setText("Clientes");

        Menu_Proveedor.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Menu_Proveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentes/img/proveedorIcon.png"))); // NOI18N
        Menu_Proveedor.setText("Proveedor");

        Menu_Inventario.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Menu_Inventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentes/img/inventarioIcon.png"))); // NOI18N
        Menu_Inventario.setText("Inventario");

        Menu_Facturas.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Menu_Facturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentes/img/facturaIcon.png"))); // NOI18N
        Menu_Facturas.setText("Crear Factura");

        Menu_Ayuda.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Menu_Ayuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentes/img/ayudaIcon.png"))); // NOI18N
        Menu_Ayuda.setText("Ayuda");

        Menu_Salir.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Menu_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componentes/img/regresarIcon.png"))); // NOI18N
        Menu_Salir.setText("Salir");
        Menu_Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_SalirMouseClicked(evt);
            }
        });

        Menu_Roles.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Menu_Roles.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Menu_Roles.setText("ROLES");

        javax.swing.GroupLayout Menu_PanelMenuLayout = new javax.swing.GroupLayout(Menu_PanelMenu);
        Menu_PanelMenu.setLayout(Menu_PanelMenuLayout);
        Menu_PanelMenuLayout.setHorizontalGroup(
            Menu_PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu_PanelMenuLayout.createSequentialGroup()
                .addGroup(Menu_PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Menu_PanelMenuLayout.createSequentialGroup()
                        .addGroup(Menu_PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Menu_PanelMenuLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(Menu_Facturas))
                            .addGroup(Menu_PanelMenuLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(Menu_PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Menu_Ayuda)
                                    .addComponent(Menu_Salir))))
                        .addGap(0, 82, Short.MAX_VALUE))
                    .addGroup(Menu_PanelMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Menu_PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Menu_Separador2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Menu_Separador, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Menu_PanelMenuLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(Menu_PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Menu_Inventario)
                                    .addGroup(Menu_PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Menu_Clientes)
                                        .addComponent(Menu_Inicio)
                                        .addComponent(Menu_Proveedor)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(Menu_PanelMenuLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(Menu_PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Menu_Foto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Menu_Roles, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Menu_PanelMenuLayout.setVerticalGroup(
            Menu_PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu_PanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Menu_Foto, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Menu_Roles)
                .addGap(20, 20, 20)
                .addComponent(Menu_Inicio)
                .addGap(44, 44, 44)
                .addComponent(Menu_Clientes)
                .addGap(39, 39, 39)
                .addComponent(Menu_Proveedor)
                .addGap(46, 46, 46)
                .addComponent(Menu_Inventario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Menu_Separador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(Menu_Facturas)
                .addGap(29, 29, 29)
                .addComponent(Menu_Separador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(Menu_Ayuda)
                .addGap(18, 18, 18)
                .addComponent(Menu_Salir)
                .addGap(19, 19, 19))
        );

        Menu_PanelFondo.add(Menu_PanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 500));

        Menu_ConPaneles.setBackground(new java.awt.Color(255, 255, 255));
        Menu_ConPaneles.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Menu_PanelClientes.setBackground(new java.awt.Color(204, 204, 204));
        Menu_PanelClientes.setPreferredSize(new java.awt.Dimension(200, 120));

        Menu_TituloClientes.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Menu_TituloClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Menu_TituloClientes.setText("Clientes");

        Menu_TituloTotal.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Menu_TituloTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Menu_TituloTotal.setText("Total");

        javax.swing.GroupLayout Menu_PanelClientesLayout = new javax.swing.GroupLayout(Menu_PanelClientes);
        Menu_PanelClientes.setLayout(Menu_PanelClientesLayout);
        Menu_PanelClientesLayout.setHorizontalGroup(
            Menu_PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu_PanelClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Menu_PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Menu_TituloClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addGroup(Menu_PanelClientesLayout.createSequentialGroup()
                        .addComponent(Menu_TituloTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Menu_PanelClientesLayout.setVerticalGroup(
            Menu_PanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu_PanelClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Menu_TituloClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(Menu_TituloTotal)
                .addGap(32, 32, 32))
        );

        Menu_PanelProductos.setBackground(new java.awt.Color(204, 204, 204));
        Menu_PanelProductos.setPreferredSize(new java.awt.Dimension(200, 120));

        Menu_TituloProductos.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Menu_TituloProductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Menu_TituloProductos.setText("Productos");

        Menu_TituloTotal2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Menu_TituloTotal2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Menu_TituloTotal2.setText("Total");

        javax.swing.GroupLayout Menu_PanelProductosLayout = new javax.swing.GroupLayout(Menu_PanelProductos);
        Menu_PanelProductos.setLayout(Menu_PanelProductosLayout);
        Menu_PanelProductosLayout.setHorizontalGroup(
            Menu_PanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu_PanelProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Menu_PanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Menu_TituloProductos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addGroup(Menu_PanelProductosLayout.createSequentialGroup()
                        .addComponent(Menu_TituloTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Menu_PanelProductosLayout.setVerticalGroup(
            Menu_PanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu_PanelProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Menu_TituloProductos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(Menu_TituloTotal2)
                .addGap(32, 32, 32))
        );

        Menu_PanelPresentacion.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout Menu_PanelPresentacionLayout = new javax.swing.GroupLayout(Menu_PanelPresentacion);
        Menu_PanelPresentacion.setLayout(Menu_PanelPresentacionLayout);
        Menu_PanelPresentacionLayout.setHorizontalGroup(
            Menu_PanelPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Menu_PanelPresentacionLayout.setVerticalGroup(
            Menu_PanelPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Menu_ConPanelesLayout = new javax.swing.GroupLayout(Menu_ConPaneles);
        Menu_ConPaneles.setLayout(Menu_ConPanelesLayout);
        Menu_ConPanelesLayout.setHorizontalGroup(
            Menu_ConPanelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu_ConPanelesLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(Menu_PanelClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(Menu_PanelProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
            .addGroup(Menu_ConPanelesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Menu_PanelPresentacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Menu_ConPanelesLayout.setVerticalGroup(
            Menu_ConPanelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu_ConPanelesLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(Menu_ConPanelesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Menu_PanelProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Menu_PanelClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Menu_PanelPresentacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Menu_PanelFondo.add(Menu_ConPaneles, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 690, 500));

        getContentPane().add(Menu_PanelFondo, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Menu_SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_SalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_Menu_SalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Menu_Ayuda;
    private javax.swing.JLabel Menu_Clientes;
    private javax.swing.JPanel Menu_ConPaneles;
    private javax.swing.JLabel Menu_Facturas;
    private javax.swing.JLabel Menu_Foto;
    private javax.swing.JLabel Menu_Inicio;
    private javax.swing.JLabel Menu_Inventario;
    private javax.swing.JPanel Menu_PanelClientes;
    private javax.swing.JPanel Menu_PanelFondo;
    private javax.swing.JPanel Menu_PanelMenu;
    private javax.swing.JPanel Menu_PanelPresentacion;
    private javax.swing.JPanel Menu_PanelProductos;
    private javax.swing.JLabel Menu_Proveedor;
    private javax.swing.JLabel Menu_Roles;
    private javax.swing.JLabel Menu_Salir;
    private javax.swing.JSeparator Menu_Separador;
    private javax.swing.JSeparator Menu_Separador2;
    private javax.swing.JLabel Menu_TituloClientes;
    private javax.swing.JLabel Menu_TituloProductos;
    private javax.swing.JLabel Menu_TituloTotal;
    private javax.swing.JLabel Menu_TituloTotal2;
    // End of variables declaration//GEN-END:variables
}
